### ISSUE TITLE
Video embeds are not responsive

### ISSUE THREAD

**Issue by mglaman** [decoupleddays/website#3]
They break the page a bit

![Screenshot_20200107-151700](https://user-images.githubusercontent.com/3698644/71930233-e19cea00-3160-11ea-9761-5125239f71fa.png)

**Comment by decoupleddays** [comment]
this is actually on the old site, which this repo doesn't have a branch for.. head on over to https://github.com/decoupleddays/decoupled-dev-days and fire up this issue there.. Though, we may have a content problem now, since we started modifying the drupal with 2020 content

**Comment by mglaman** [comment]
But we copied the same styles, correct? And we can still make sure the new theme has styles for responsive videos, yeah?
